# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0457a4cb7e0ea1edfe5f4300efd7b6fce95e1ca35f31c2bf3886a33e2cc54080fe94924bb9e663bc0dced154f1aa3819d624296201f7c7309cc30d2208f288ac

test:
  secret_key_base: 1e6ba9b00b81c3390aae571fab17ad0e304a3c1220694fd8b17a1852c63e2f12bf66f7c4fd832463bf7a8152d9530aa01ccc63420ac5de73e97b5f54b81c59a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
