# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64a9d7ebe946b95e5bf40ef19884740e142438792f2933e8678592a5842e43f37de82b656044818cd5bf162c4a3b7ee3a7c7c8a2d9c4a084dfd390fd7c08b615

test:
  secret_key_base: 90225b1135be6372ef636676fc53e428b8f0dd654677042ea102b51c3cc6203b2b41404360949b15b2c8d862f24190648697d9e5a7586da5dadb870bafee5627

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
