# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de401289e3f3489dab037d0ad7934f8979465fc818042fd0f6164ae46ae457f2efa70eec85f08e366e71b857e8376019c578686428cac3775b2603a135fa6911

test:
  secret_key_base: d4bfdec2cf3e71f8394d5489b60094577a500dcd87b1b8eddba22ec12cebdbc0dc91c43061b6d741a1946d71fc138da1ac4ed154cb16c1db882a4b63dd8fbdea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
