# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9a648ca856eb00b74f9a1b791f3ef4e540a03429a3987eaf6ef816f709deef3b6b09535d806f42627e9fcceaf6e58214543693ab8edb44b3cf1f5b15e467ffe

test:
  secret_key_base: 2385984d38ef67b64872622d1d1e7eb05a91ef64aabf31919a9763032921d1f90f54ab5ff38c74973474650f820fe4d99f0a9ba45e3c88dcd9d8c6d29fbdb9e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
