# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25310e9a4344da2d2ddaeadafef3a0bb0c911d1dfa579a0fc69892d3b8dc5342427fdff974e9219a42b087b0851cb6f6c894557fe3bacf72e33606ff6dd53ff3

test:
  secret_key_base: 82e0c5f6c87269719c6afffe3ffa39ad565438441b7b4af8479607dab38ec331c1f32ddd5c9e0fb616c714f0b0f3aa27005b6140af8076bf58702b3a2860161a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
