# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 400b21ba2d040bc43898c5027ce10f142f06dbd7ee02f10888137bde356f99ef41f19c4970ad054a8abae71312c8c8e73b99877ba3c47f01c07da553ce27e44f

test:
  secret_key_base: 0919285bdf2fabf8b50812d6cdc2f724f0ef4ea608171ba56896aab0c10fee7f49ea57744de5d452dda9b357bf3e7741624022d53a8e5170613f2380dad5c325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
