Continent.create name: 'Africa'
Continent.create name: 'Asia'
Continent.create name: 'Antartica'
Continent.create name: 'Australia'
Continent.create name: 'Europe'
Continent.create name: 'North America'
Continent.create name: 'South America'
