# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 664628a877f713e81082a3deb88d5847850dfc357b19fc658d7ac5908d2237cfb0a20fe30d6dabf681f788d2e8eedc5f64c8d597208ed2638796c4ed17d350fe

test:
  secret_key_base: 528f5cf8a0e789d09c2e0a23bba60967d4754be2f6eefc6b0b83eba5ec16fbde6e353ac00c670e44b36d252ccf539df18f78bef1f6ec0c3c7693bb42f8a689bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
