# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9d26903824663b0e8bdcc0bbf463124c5b813d87f9a01d6be4b7a190c3add58b9c6110a7cb2c49028c9042507a1cb01acd63a319fa7b78fd6ca60b3ebe3bc76

test:
  secret_key_base: fefec374699ef3bc27a28ded105bd20a567963295baf0eef24879e3f45d53740a732fa853c399480c3e6b4843ca6b0532b45b3981679c99f62aa01860812be4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
